### ISSUE TITLE
RegEx doesn't match for Kindle

### ISSUE THREAD

**Issue by writtmeyer** [mttkay/replicant#1]
adb devices -l with a Kindle connected gives "D059A0A0245404LB       device usb:3-2". So no "model:" info is contained in this output and thus the RegEx in command.rb on line 124 doesn't match.

Since I can barely read ruby I cannot provide a pull request.

**Comment by mttkay** [comment]
Good catch, thanks!

**Comment by jameswald** [comment]
This repo may help prettify the device names by mapping from the usb vendor id to vendor name:
https://github.com/apkudo/adbusbini

**Comment by mttkay** [comment]
I should really add a Rakefile and write unit tests me thinks.

**Comment by mttkay** [comment]
Feel free to reopen if it's still not working. The script now shows devices without a model tag as "unknown device". There might be something smarter to do than that, definitely open for suggestions here.

This commit also fixed the issue where a device ID contains a colon, such as when connecting a Google TV over the network.
