### ISSUE TITLE
Genymotion emulator name issue

### ISSUE THREAD

**Issue by mrmike** [mttkay/replicant#10]
Hi,
I'm using Genymotion emulator for my development work. Replicat shell detects Genymotion emulator as a unknown device.
`192.168.56.101:5555  [unknown device]`

and to select this emulator I need to use
`!device dev1`

It's not a big issue, but I decided to report this anyway.

**Comment by mttkay** [comment]
yeah the current device name detection sucks. I only look at the `model:` part, which is missing in many cases (someone reported a Kindle not being reported that way either.)

I'll look into ways to make this smarter. Thanks!

**Comment by mttkay** [comment]
```
192.168.56.102:5555    device product:vbox86tp model:WXGA_10_1_Tablet___4_2_2___API_17 device:vbox86tp

192.168.56.101:5555    device product:vbox86p model:Galaxy_Nexus___4_2_2___API_17 device:vbox86p
```

Actually, model does seem to exist.

**Comment by mttkay** [comment]
Related to #1

**Comment by mttkay** [comment]
I'm investigating this, but quickly testing the regex being used against the device strings provided seems to check out. Don't actually have Genymotion installed, I guess I should fix that first.

**Comment by mttkay** [comment]
Some device strings I used for testing:

```
192.168.56.102:5555    device product:vbox86tp model:WXGA_10_1_Tablet___4_2_2___API_17 device:vbox86tp
emulator-5558  device
0A3C294805017006       device usb:1-1 product:full_toroplus model:Full_AOSP_on_Toroplus device:toroplus
015d2994ec2xxx         device usb:2-1.5 product:nakasi model:Nexus_7 device:grouper
D059A0A0245404LB device usb:3-2
```

**Comment by mrmike** [comment]
Ok, I will check this with Genymotion emulator.

2013/11/18 Matthias Käppler notifications@github.com

> Some device strings I used for testing:
> 
> 192.168.56.102:5555    device product:vbox86tp model:WXGA_10_1_Tablet___4_2_
> 2___API_17 device:vbox86tp
> emulator-5558  device
> 0A3C294805017006       device usb:1-1 product:full_toroplus model:Full_AOSP_on_Toroplus device:toroplus
> 015d2994ec2xxx         device usb:2-1.5 product:nakasi model:Nexus_7 device:grouper
> D059A0A0245404LB device usb:3-2
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/mttkay/replicant/issues/10#issuecomment-28718899
> .

## 

Pozdrawiam
Micha³ Moczulski

**Comment by mttkay** [comment]
This should be fixed, and genymotion devices should now be recognized. Can you test against the latest master? 

Note that devices are now simply selected by index or serial number, not dev1, emu2, etc.

**Comment by mrmike** [comment]
I've just tested changes from a new commit and everything works fine.
