### ISSUE TITLE
!device not working for device named "0123456789ABCDEF"

### ISSUE THREAD

**Issue by bizzguy** [mttkay/replicant#16]
Following is the result of !devices for my device

  0123456789ABCDEF     [unknown device]

Tried to set device with

  !device 0123456789ABCDEF

Received following error

  Invalid arguments. Ex.: !device [emulator-5554|emu1|<serial>|dev1|...]

**Comment by mrmike** [comment]
Try to set device with
`!device dev1`

Related #1 #10

**Comment by bizzguy** [comment]
Thanks!  That worked like a charm.

**Comment by mttkay** [comment]
Still, this is a bug. It should work. I'm actually about to revise how this will work entirely. Thanks for reporting.

**Comment by mttkay** [comment]
Can you pull from master and retest? I vastly improved device recognition, selection and command output 

From now on, select devices purely by list index or serial no

**Comment by mttkay** [comment]
Closing this for now, it should be fixed by the recent rewrite of the !device command.

Feel free to reopen if you still have issues with this.
