### ISSUE TITLE
Problem finding command history

### ISSUE THREAD

**Issue by bizzguy** [mttkay/replicant#17]
I'm trying to see the history using the up arrow key.  The machine is a MacBook Pro with OSX 10.9.  The up arrow outputs the following:

^[[A

Any ideas?  Thanks.

**Comment by mrmike** [comment]
Simply install http://utopia.knoware.nl/~hlub/rlwrap/

If you're mac user the easiest way to install rlwrap is by using MacPorts (http://brew.sh/)
1) Install Homebrew if you don't have already installed
 `ruby -e "$(curl -fsSL https://raw.github.com/mxcl/homebrew/go)"`
2) and then install rlwrap
`brew install rlwrap`

**Comment by bizzguy** [comment]
Worked perfectly.  Thanks.

**Comment by mttkay** [comment]
Thanks @mrmike :-)
